// THIS FILE WAS AUTO GENERATED BY uppaal2c.exe DO NOT MODIFY!!!

#include "model.h"
#include "uppaal2c_private.h"

#ifdef __cplusplus
extern "C" { 
#endif
// Channels
const U2C_CHANNEL_DATA GLOBAL_CHANNEL_VAR_press_DATA = // chan press
    {
        DBG_FIELD("chan press[]")	// name
        U2C_FALSE,				// urgent
        U2C_FALSE,				// broadcast
    };

U2C_CHANNEL GLOBAL_CHANNEL_VAR_press = // chan press
    {
        &GLOBAL_CHANNEL_VAR_press_DATA,         // data
        NULL,              // firedcb
        NULL,              // context
        U2C_FALSE,              // cur_fired
        U2C_FALSE,              // prev_fired
    };


// ChannelsList
U2C_CHANNEL* ALL_CHANNELS[TOTAL_CHANNEL_COUNT] = 
    {
        &GLOBAL_CHANNEL_VAR_press,
    };


U2C_SYSTEM_STATE U2C_StateVars;

void init_system_variables() {
}

// Process - Light

static U2C_BOOL guardfunc_Light_TRANS_low__off__0()
{
    return (((_U2C_GET_CLK(U2C_StateVars.u2c_clk_t_GLOBAL_y))>=(5)));
};
const U2C_TRANSITION_DATA Light_TRANS_low__off__0_DATA =
    {
        DBG_FIELD("low__off__0")	// name
        &Light_STATE_off,				// target
        &GLOBAL_CHANNEL_VAR_press,				// receive
        NULL,				// send
        guardfunc_Light_TRANS_low__off__0,               // guard
        NULL,               // update
    };

U2C_TRANSITION Light_TRANS_low__off__0 =
    {
        &Light_TRANS_low__off__0_DATA,         // data
        NULL,              // transition_execute_cb
        NULL,              // context
    };

static void updatefunc_Light_TRANS_off__low__0()
{
    _U2C_SET_CLK(U2C_StateVars.u2c_clk_t_GLOBAL_y, ((0)));
};
const U2C_TRANSITION_DATA Light_TRANS_off__low__0_DATA =
    {
        DBG_FIELD("off__low__0")	// name
        &Light_STATE_low,				// target
        &GLOBAL_CHANNEL_VAR_press,				// receive
        NULL,				// send
        NULL,               // guard
        updatefunc_Light_TRANS_off__low__0,               // update
    };

U2C_TRANSITION Light_TRANS_off__low__0 =
    {
        &Light_TRANS_off__low__0_DATA,         // data
        NULL,              // transition_execute_cb
        NULL,              // context
    };

const U2C_TRANSITION_DATA Light_TRANS_bright__off__0_DATA =
    {
        DBG_FIELD("bright__off__0")	// name
        &Light_STATE_off,				// target
        &GLOBAL_CHANNEL_VAR_press,				// receive
        NULL,				// send
        NULL,               // guard
        NULL,               // update
    };

U2C_TRANSITION Light_TRANS_bright__off__0 =
    {
        &Light_TRANS_bright__off__0_DATA,         // data
        NULL,              // transition_execute_cb
        NULL,              // context
    };

static U2C_BOOL guardfunc_Light_TRANS_low__bright__0()
{
    return (((_U2C_GET_CLK(U2C_StateVars.u2c_clk_t_GLOBAL_y))<(5)));
};
const U2C_TRANSITION_DATA Light_TRANS_low__bright__0_DATA =
    {
        DBG_FIELD("low__bright__0")	// name
        &Light_STATE_bright,				// target
        &GLOBAL_CHANNEL_VAR_press,				// receive
        NULL,				// send
        guardfunc_Light_TRANS_low__bright__0,               // guard
        NULL,               // update
    };

U2C_TRANSITION Light_TRANS_low__bright__0 =
    {
        &Light_TRANS_low__bright__0_DATA,         // data
        NULL,              // transition_execute_cb
        NULL,              // context
    };

const U2C_TRANSITION* Light_STATE_bright_OUT[] = 
    {
        &Light_TRANS_bright__off__0, // bright__off__0
    NULL
    };

const U2C_STATENODE_DATA Light_STATE_bright_DATA =
    {
        DBG_FIELD("bright")	// name
        (U2C_TRANSITION* const*)&Light_STATE_bright_OUT,	// target
        U2C_StateNormal, // mode
        NULL, // guard
    };

U2C_STATENODE Light_STATE_bright =
    {
        &Light_STATE_bright_DATA,         // data
        NULL,              // state_enter
        NULL,              // state_leave
        NULL,              // context
    };

const U2C_TRANSITION* Light_STATE_low_OUT[] = 
    {
        &Light_TRANS_low__bright__0, // low__bright__0
        &Light_TRANS_low__off__0, // low__off__0
    NULL
    };

const U2C_STATENODE_DATA Light_STATE_low_DATA =
    {
        DBG_FIELD("low")	// name
        (U2C_TRANSITION* const*)&Light_STATE_low_OUT,	// target
        U2C_StateNormal, // mode
        NULL, // guard
    };

U2C_STATENODE Light_STATE_low =
    {
        &Light_STATE_low_DATA,         // data
        NULL,              // state_enter
        NULL,              // state_leave
        NULL,              // context
    };

const U2C_TRANSITION* Light_STATE_off_OUT[] = 
    {
        &Light_TRANS_off__low__0, // off__low__0
    NULL
    };

const U2C_STATENODE_DATA Light_STATE_off_DATA =
    {
        DBG_FIELD("off")	// name
        (U2C_TRANSITION* const*)&Light_STATE_off_OUT,	// target
        U2C_StateNormal, // mode
        NULL, // guard
    };

U2C_STATENODE Light_STATE_off =
    {
        &Light_STATE_off_DATA,         // data
        NULL,              // state_enter
        NULL,              // state_leave
        NULL,              // context
    };

const U2C_TASK_DATA Light_TASK_DATA = 
    {
        DBG_FIELD("Light_TASK")	// name
        &Light_STATE_off, // initState
    };

U2C_TASK Light_TASK = 
    {
        &Light_TASK_DATA,         // data
        NULL,              // process_start
        NULL,              // context
        &Light_STATE_off,              // current
        U2C_FALSE,              // stepped
        U2C_FALSE,              // normal_stepped
        U2C_ProcessInit,        // state
    };


U2C_TASK* U2C_TASK_LIST[1] =
{
   NULL,
};



#ifdef __cplusplus
} // extern "C" 
#endif
