//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uppaal2c.templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uppaal2c.templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///
        ///#include &quot;uppaal2c.h&quot;
        ///#include &quot;uppaal2c_platform.h&quot;
        ///#include &quot;uppaal2c_types.h&quot;
        ///#include &quot;uppaal2c_private.h&quot;
        ///#include &quot;model.h&quot;
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///#ifdef _MSC_VER
        ///#pragma warning(disable : 4127)
        ///#en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c___c {
            get {
                return ResourceManager.GetString("uppaal2c___c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///#pragma once
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///// public interface in this file
        ///
        ///#include &quot;uppaal2c_platform.h&quot;
        ///
        ///typedef enum
        ///{
        ///	U2C_SendChannelModeNone, U2C_SendChannelModeSet, U2C_SendChannelModeToggle, U2C_SendChan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c___h {
            get {
                return ResourceManager.GetString("uppaal2c___h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///#pragma once
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///#ifdef C_INLINE_SUPPORTED
        ///#define U2C_INLINE inline
        ///#else
        ///#define U2C_INLINE 
        ///#endif
        ///
        ///typedef enum U2C_SendChannelMode U2C_SendChannelMode;
        ///typedef enum U2C_ReceiveChann [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c_platform___h {
            get {
                return ResourceManager.GetString("uppaal2c_platform___h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ///#include &quot;uppaal2c_platform.h&quot;
        ///#include &quot;uppaal2c.h&quot;
        ///#include &lt;cmsis_os.h&gt;
        ///
        ///void u2c_platform_gpio_init_in(U2C_PLATFORM_GPIO* gpioptr, U2C_PLATFORM_PIN_NAME pin, U2C_PLATFORM_PIN_MODE mode) 
        ///{ 
        ///	gpio_init_in(&amp;gpioptr-&gt;gpio, pin); 
        ///	gpio_mode(&amp;gpioptr-&gt;gpio, mode);
        ///}
        ///
        ///void u2c_platform_gpio_init_interrupt(U2C_PLATFORM_GPIO* gpioptr, U2C_PLATFORM_PIN_NAME pin, U2C_PLATFORM_PIN_MODE mode,
        ///				u2c_gpio_irq_handler_cb_t cb, void* ctx)
        ///{
        ///	gpio_init_in(&amp;(gpioptr)-&gt;gpio, pin);
        ///	gpio_mod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c_platform_cmsis___c {
            get {
                return ResourceManager.GetString("uppaal2c_platform_cmsis___c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///#pragma once
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///#include &quot;PinNames.h&quot;
        ///#include &quot;cmsis_os.h&quot;
        ///#include &quot;gpio_api.h&quot;
        ///#include &quot;gpio_irq_api.h&quot;
        ///#include &quot;us_ticker_api.h&quot;
        ///
        ///#define MBED_USE_MACROS
        ///
        ///// bool
        ///typedef int U2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c_platform_cmsis___h {
            get {
                return ResourceManager.GetString("uppaal2c_platform_cmsis___h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///#pragma once
        ///
        ///#include &lt;stdlib.h&gt; // for NULL
        ///#include &quot;uppaal2c_platform.h&quot;
        ///#include &quot;uppaal2c_types.h&quot;
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///// clocks
        ///#define _U2C_GET_TICK() DISPATCHER._tick
        ///
        ///#define _U2C_INIT_CLK(clk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c_private___h {
            get {
                return ResourceManager.GetString("uppaal2c_private___h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // VERSION: 1
        ////*
        ///*  UPPAAAL2C (c) 2014 Ariel Eizenberg - arieleiz@seas.upenn.edu.
        ///*
        ///*    This file is part of UPPAAAL2C. You can redistribute it and/or modify
        ///*    it under the terms of the Academic Free License 3.0
        ///*	  (http://opensource.org/licenses/AFL-3.0).
        ///*
        ///*/
        ///#pragma once
        ///
        ///#include &quot;uppaal2c.h&quot;
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///// forward declarations
        ///typedef struct U2C_STATENODE_DATA U2C_STATENODE_DATA;
        ///typedef struct U2C_STATENODE U2C_STATENODE;
        ///typedef struct U2C_TRANSIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uppaal2c_types___h {
            get {
                return ResourceManager.GetString("uppaal2c_types___h", resourceCulture);
            }
        }
    }
}
